'use client'

import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { getExpenseUnits, type ExpenseUnit } from '@/api/expense'
import { createInventoryItem, createInventoryReceipt, getInventoryItems, getInventoryStock, updateInventoryItem, type InventoryItem, type InventoryPurchaseUnit } from '@/api/inventory'
import { useI18n } from '@/lib/i18n'
import { toast } from 'sonner'

type Tab = 'items' | 'receipts'
const labels = {
    vi: { title: 'Kho nguyên liệu', items: 'Nguyên liệu', receipts: 'Nhập kho', name: 'Tên nguyên liệu', stockUnit: 'Đơn vị tồn kho', safety: 'Mức tồn an toàn', last: 'Kiểm lần cuối', purchase: 'Quy cách nhập', unit: 'Đơn vị mua', factor: 'Hệ số', addRule: 'Thêm quy cách', save: 'Lưu', add: 'Thêm', edit: 'Sửa', cancel: 'Hủy', choose: 'Chọn nguyên liệu', quantity: 'Số lượng', price: 'Đơn giá', current: 'Tồn hiện tại', invalid: 'Quy cách không hợp lệ' },
    en: { title: 'Inventory', items: 'Ingredients', receipts: 'Receipts', name: 'Ingredient name', stockUnit: 'Stock unit', safety: 'Safety stock', last: 'Last checked', purchase: 'Purchase units', unit: 'Purchase unit', factor: 'Factor', addRule: 'Add unit', save: 'Save', add: 'Add', edit: 'Edit', cancel: 'Cancel', choose: 'Choose ingredient', quantity: 'Quantity', price: 'Unit price', current: 'Current stock', invalid: 'Invalid purchase unit' },
    'zh-TW': { title: '原料庫存', items: '原料', receipts: '進貨', name: '原料名稱', stockUnit: '庫存單位', safety: '安全庫存', last: '上次盤點', purchase: '進貨規格', unit: '進貨單位', factor: '換算係數', addRule: '新增規格', save: '儲存', add: '新增', edit: '編輯', cancel: '取消', choose: '選擇原料', quantity: '數量', price: '單價', current: '目前庫存', invalid: '進貨規格無效' },
} as const

export default function InventoryPanel({ initialTab = 'items' }: { initialTab?: Tab }) {
    const { locale } = useI18n(); const t = labels[locale]; const client = useQueryClient()
    const [tab, setTab] = useState<Tab>(initialTab); const [name, setName] = useState(''); const [stockUnit, setStockUnit] = useState('piece'); const [rules, setRules] = useState<InventoryPurchaseUnit[]>([]); const [ruleUnit, setRuleUnit] = useState(''); const [factor, setFactor] = useState('1'); const [safetyStock, setSafetyStock] = useState('0'); const [editing, setEditing] = useState<InventoryItem | null>(null); const [selectedId, setSelectedId] = useState(''); const [receiptUnit, setReceiptUnit] = useState(''); const [quantity, setQuantity] = useState('1'); const [price, setPrice] = useState('0')
    const { data: units = [] } = useQuery<ExpenseUnit[]>({ queryKey: ['expense-units'], queryFn: () => getExpenseUnits() }); const { data: items = [] } = useQuery({ queryKey: ['inventory-items'], queryFn: getInventoryItems }); const { data: stock = [] } = useQuery({ queryKey: ['inventory-stock'], queryFn: getInventoryStock }); const selected = items.find((item) => item._id === selectedId)
    const refresh = () => { void client.invalidateQueries({ queryKey: ['inventory-items'] }); void client.invalidateQueries({ queryKey: ['inventory-stock'] }); void client.invalidateQueries({ queryKey: ['expenses'] }) }
    const reset = () => { setName(''); setStockUnit('piece'); setRules([]); setRuleUnit(''); setFactor('1'); setSafetyStock('0'); setEditing(null) }
    const currentName = editing?.name ?? name; const currentStockUnit = editing?.stockUnitCode ?? stockUnit; const currentRules = editing?.purchaseUnits ?? rules; const setCurrentRules = (next: InventoryPurchaseUnit[]) => editing ? setEditing({ ...editing, purchaseUnits: next }) : setRules(next)
    const addRule = () => { const value = Number(factor); if (!ruleUnit || value <= 0 || !Number.isFinite(value) || currentRules.some((rule) => rule.unitCode === ruleUnit)) return toast.error(t.invalid); setCurrentRules([...currentRules.filter((rule) => rule.unitCode !== currentStockUnit), { unitCode: ruleUnit, conversionFactor: value }]); setRuleUnit(''); setFactor('1') }
    const normalizedRules = [{ unitCode: currentStockUnit, conversionFactor: 1 }, ...currentRules.filter((rule) => rule.unitCode !== currentStockUnit)]
    const create = useMutation({ mutationFn: createInventoryItem, onSuccess: () => { refresh(); reset() } }); const update = useMutation({ mutationFn: updateInventoryItem, onSuccess: () => { refresh(); reset() } }); const receipt = useMutation({ mutationFn: createInventoryReceipt, onSuccess: () => { refresh(); setQuantity('1'); setPrice('0') } })
    const save = () => { const data = { name: currentName, stockUnitCode: currentStockUnit, purchaseUnits: normalizedRules, minimumStock: Math.max(0, Number(editing ? editing.minimumStock : safetyStock) || 0), note: editing?.note, active: editing?.active ?? true }; if (editing) update.mutate({ id: editing._id, data }); else create.mutate(data) }
    return <div className='flex h-full min-h-0 flex-col gap-4 overflow-y-auto p-4 md:p-6'><h1 className='text-2xl font-bold'>{t.title}</h1><div className='flex gap-2 border-b pb-2'>{([['items', t.items], ['receipts', t.receipts]] as const).map(([id, label]) => <Button key={id} variant={tab === id ? 'default' : 'outline'} onClick={() => setTab(id)}>{label}</Button>)}</div>
        {tab === 'items' && <Card><CardHeader><CardTitle>{editing ? t.edit : t.add}</CardTitle></CardHeader><CardContent className='space-y-4'><div className='grid gap-3 md:grid-cols-3'><Input value={currentName} placeholder={t.name} onChange={(e) => editing ? setEditing({ ...editing, name: e.target.value }) : setName(e.target.value)} /><select className='h-9 rounded-md border px-3' value={currentStockUnit} onChange={(e) => editing ? setEditing({ ...editing, stockUnitCode: e.target.value }) : setStockUnit(e.target.value)}>{units.map((unit) => <option key={unit.code} value={unit.code}>{unit.names[locale]}</option>)}</select><Input type='number' min='0' step='any' value={editing ? editing.minimumStock : safetyStock} placeholder={t.safety} onChange={(e) => editing ? setEditing({ ...editing, minimumStock: Number(e.target.value) }) : setSafetyStock(e.target.value)} /></div><div className='space-y-2 rounded border p-3'><p className='font-medium'>{t.purchase}</p><div className='flex flex-wrap gap-2'>{normalizedRules.map((rule) => <span key={rule.unitCode} className='rounded bg-muted px-2 py-1 text-sm'>{rule.unitCode} × {rule.conversionFactor}{rule.unitCode !== currentStockUnit && <button type='button' className='ml-1' onClick={() => setCurrentRules(currentRules.filter((entry) => entry.unitCode !== rule.unitCode))}>×</button>}</span>)}</div><div className='grid gap-2 md:grid-cols-3'><select className='h-9 rounded-md border px-3' value={ruleUnit} onChange={(e) => setRuleUnit(e.target.value)}><option value=''>{t.unit}</option>{units.map((unit) => <option key={unit.code} value={unit.code}>{unit.names[locale]}</option>)}</select><Input type='number' min='0.000001' value={factor} onChange={(e) => setFactor(e.target.value)} /><Button type='button' variant='outline' onClick={addRule}>{t.addRule}</Button></div></div><Button disabled={!currentName || !currentStockUnit} onClick={save}>{editing ? t.save : t.add}</Button>{editing && <Button className='ml-2' variant='outline' onClick={reset}>{t.cancel}</Button>}<Table><TableHeader><TableRow><TableHead>{t.name}</TableHead><TableHead>{t.stockUnit}</TableHead><TableHead>{t.safety}</TableHead><TableHead>{t.current}</TableHead><TableHead /></TableRow></TableHeader><TableBody>{stock.map((item) => <TableRow key={item._id}><TableCell>{item.name}</TableCell><TableCell>{item.stockUnitCode}</TableCell><TableCell>{item.minimumStock}</TableCell><TableCell>{item.currentQuantity}</TableCell><TableCell><Button size='sm' variant='outline' onClick={() => { setEditing(item); setRules(item.purchaseUnits.filter((rule) => rule.unitCode !== item.stockUnitCode)) }}>{t.edit}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}
        {tab === 'receipts' && <Card><CardHeader><CardTitle>{t.receipts}</CardTitle></CardHeader><CardContent className='grid gap-3 md:grid-cols-4'><select className='h-9 rounded-md border px-3' value={selectedId} onChange={(e) => { setSelectedId(e.target.value); const item = items.find((entry) => entry._id === e.target.value); setReceiptUnit(item?.stockUnitCode || '') }}><option value=''>{t.choose}</option>{items.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><select className='h-9 rounded-md border px-3' value={receiptUnit} onChange={(e) => setReceiptUnit(e.target.value)} disabled={!selected}>{selected?.purchaseUnits.map((rule) => <option key={rule.unitCode} value={rule.unitCode}>{rule.unitCode}</option>)}</select><Input type='number' min='0.001' value={quantity} onChange={(e) => setQuantity(e.target.value)} placeholder={t.quantity} /><Input type='number' min='0' value={price} onChange={(e) => setPrice(e.target.value)} placeholder={t.price} /><Button disabled={!selected || receipt.isPending} onClick={() => receipt.mutate({ lines: [{ inventoryItemId: selectedId, quantity: Number(quantity), unitCode: receiptUnit, unitPrice: Number(price) }] })}>{t.save}</Button></CardContent></Card>}
    </div>
}
