'use client'

import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { getExpenseUnits, type ExpenseUnit } from '@/api/expense'
import { createInventoryItem, createInventoryReceipt, createInventoryStocktake, getInventoryItems, getInventoryStock, updateInventoryItem, type InventoryItem } from '@/api/inventory'
import { useI18n } from '@/lib/i18n'
import { toast } from 'sonner'

type Tab = 'items' | 'receipts' | 'stocktake'
type ApiError = { response?: { status?: number } }
const text = { vi: { title: 'Kho nguyên liệu', hint: 'Nhập kho và kiểm kê', items: 'Nguyên liệu', receipts: 'Nhập kho', stocktake: 'Kiểm kho', addItem: 'Thêm nguyên liệu', itemName: 'Tên nguyên liệu, ví dụ: Nước suối', stockUnit: 'Đơn vị tồn kho', add: 'Thêm', edit: 'Sửa', save: 'Lưu', choose: 'Chọn nguyên liệu', quantity: 'Số lượng', price: 'Đơn giá', receipt: 'Lưu phiếu nhập', system: 'Tồn hệ thống', actual: 'Tồn thực tế', saveStock: 'Lưu kiểm kho', list: 'Danh sách nguyên liệu', count: 'Tổng cộng', page: 'Trang', prev: 'Trước', next: 'Sau', duplicate: 'Nguyên liệu đã tồn tại trong cửa hàng.', error: 'Không thể lưu nguyên liệu.' }, en: { title: 'Inventory', hint: 'Receipts and stocktakes', items: 'Ingredients', receipts: 'Receipts', stocktake: 'Stocktake', addItem: 'Add ingredient', itemName: 'Ingredient name, e.g. Bottled water', stockUnit: 'Stock unit', add: 'Add', edit: 'Edit', save: 'Save', choose: 'Choose ingredient', quantity: 'Quantity', price: 'Unit price', receipt: 'Save receipt', system: 'System stock', actual: 'Actual stock', saveStock: 'Save stocktake', list: 'Ingredient list', count: 'Total', page: 'Page', prev: 'Previous', next: 'Next', duplicate: 'This ingredient already exists in the store.', error: 'Unable to save ingredient.' }, 'zh-TW': { title: '原料庫存', hint: '進貨與盤點', items: '原料', receipts: '進貨', stocktake: '盤點', addItem: '新增原料', itemName: '原料名稱，例如：礦泉水', stockUnit: '庫存單位', add: '新增', edit: '編輯', save: '儲存', choose: '選擇原料', quantity: '數量', price: '單價', receipt: '儲存進貨單', system: '系統庫存', actual: '實際庫存', saveStock: '儲存盤點', list: '原料清單', count: '總計', page: '頁', prev: '上一頁', next: '下一頁', duplicate: '此原料已存在於此分店。', error: '無法儲存原料。' } } as const

export default function InventoryPanel({ initialTab = 'items' }: { initialTab?: Tab }) {
  const { locale } = useI18n(); const t = text[locale]; const queryClient = useQueryClient(); const [tab, setTab] = useState<Tab>(initialTab); const [name, setName] = useState(''); const [stockUnitCode, setStockUnitCode] = useState('piece'); const [selectedItem, setSelectedItem] = useState(''); const [quantity, setQuantity] = useState('1'); const [unitPrice, setUnitPrice] = useState('0'); const [actualQuantity, setActualQuantity] = useState('0'); const [itemPage, setItemPage] = useState(1); const [editing, setEditing] = useState<InventoryItem | null>(null); const pageSize = 8
  const { data: units = [] } = useQuery<ExpenseUnit[]>({ queryKey: ['expense-units'], queryFn: () => getExpenseUnits() }); const { data: items = [] } = useQuery({ queryKey: ['inventory-items'], queryFn: getInventoryItems }); const { data: stock = [] } = useQuery({ queryKey: ['inventory-stock'], queryFn: getInventoryStock }); const invalidate = () => { queryClient.invalidateQueries({ queryKey: ['inventory-items'] }); queryClient.invalidateQueries({ queryKey: ['inventory-stock'] }); queryClient.invalidateQueries({ queryKey: ['expenses'] }) }; const selected = items.find((item) => item._id === selectedItem); const stockRow = stock.find((item) => item._id === selectedItem); const totalPages = Math.max(1, Math.ceil(items.length / pageSize)); const visibleItems = items.slice((itemPage - 1) * pageSize, itemPage * pageSize)
  const addItem = useMutation({ mutationFn: createInventoryItem, onSuccess: () => { invalidate(); setName('') }, onError: (error: ApiError) => toast.error(error?.response?.status === 409 ? t.duplicate : t.error) }); const editItem = useMutation({ mutationFn: updateInventoryItem, onSuccess: () => { invalidate(); setEditing(null) }, onError: (error: ApiError) => toast.error(error?.response?.status === 409 ? t.duplicate : t.error) }); const addReceipt = useMutation({ mutationFn: createInventoryReceipt, onSuccess: () => { invalidate(); setQuantity('1'); setUnitPrice('0') } }); const addStocktake = useMutation({ mutationFn: createInventoryStocktake, onSuccess: invalidate })
  return <div className='flex h-full min-h-0 flex-col gap-4 overflow-y-auto p-4 md:p-6'><div><h1 className='text-2xl font-bold'>{t.title}</h1><p className='text-sm text-muted-foreground'>{t.hint}</p></div><div className='flex gap-2 border-b pb-2'>{([['items', t.items], ['receipts', t.receipts], ['stocktake', t.stocktake]] as const).map(([value, label]) => <Button key={value} variant={tab === value ? 'default' : 'outline'} onClick={() => setTab(value)}>{label}</Button>)}</div>
    {tab === 'items' && <Card><CardHeader><CardTitle>{editing ? t.edit : t.addItem}</CardTitle></CardHeader><CardContent className='space-y-4'><div className='grid gap-3 md:grid-cols-[2fr_1fr_auto] md:items-end'><Input value={editing?.name ?? name} onChange={(e) => editing ? setEditing({ ...editing, name: e.target.value }) : setName(e.target.value)} placeholder={t.itemName} /><select aria-label={t.stockUnit} className='h-9 w-full rounded-md border bg-background px-3 text-sm' value={editing?.stockUnitCode ?? stockUnitCode} onChange={(e) => editing ? setEditing({ ...editing, stockUnitCode: e.target.value }) : setStockUnitCode(e.target.value)}>{units.map((unit) => <option key={unit.code} value={unit.code}>{unit.names[locale]}</option>)}</select><div className='flex gap-2'>{editing ? <><Button onClick={() => editItem.mutate({ id: editing._id, data: editing })}>{t.save}</Button><Button variant='outline' onClick={() => setEditing(null)}>×</Button></> : <Button disabled={!name || addItem.isPending} onClick={() => addItem.mutate({ name, stockUnitCode, purchaseUnits: [{ unitCode: stockUnitCode, conversionFactor: 1 }], minimumStock: 0 })}>{t.add}</Button>}</div></div><div className='overflow-auto rounded border'><Table><TableHeader><TableRow><TableHead>{t.itemName}</TableHead><TableHead>{t.stockUnit}</TableHead><TableHead>{t.edit}</TableHead></TableRow></TableHeader><TableBody>{visibleItems.map((item) => <TableRow key={item._id}><TableCell>{item.name}</TableCell><TableCell>{item.stockUnitCode}</TableCell><TableCell><Button size='sm' variant='outline' onClick={() => setEditing(item)}>{t.edit}</Button></TableCell></TableRow>)}</TableBody></Table></div><div className='flex items-center justify-between text-sm text-muted-foreground'><span>{t.count}: {items.length} · {t.page} {itemPage}/{totalPages}</span><div className='flex gap-2'><Button size='sm' variant='outline' disabled={itemPage === 1} onClick={() => setItemPage((value) => value - 1)}>{t.prev}</Button><Button size='sm' variant='outline' disabled={itemPage === totalPages} onClick={() => setItemPage((value) => value + 1)}>{t.next}</Button></div></div></CardContent></Card>}
    {tab === 'receipts' && <Card><CardHeader><CardTitle>{t.receipts}</CardTitle></CardHeader><CardContent className='grid gap-3 md:grid-cols-4 md:items-end'><select aria-label={t.choose} className='h-9 w-full rounded-md border bg-background px-3 text-sm' value={selectedItem} onChange={(e) => setSelectedItem(e.target.value)}><option value=''>{t.choose}</option>{items.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><Input aria-label={t.quantity} type='number' min='0.001' value={quantity} onChange={(e) => setQuantity(e.target.value)} placeholder={t.quantity} /><Input aria-label={t.price} type='number' min='0' value={unitPrice} onChange={(e) => setUnitPrice(e.target.value)} placeholder={t.price} /><Button disabled={!selectedItem || addReceipt.isPending} onClick={() => addReceipt.mutate({ lines: [{ inventoryItemId: selectedItem, quantity: Number(quantity), unitCode: selected?.stockUnitCode || 'piece', unitPrice: Number(unitPrice) }] })}>{t.receipt}</Button></CardContent></Card>}
    {tab === 'stocktake' && <Card><CardHeader><CardTitle>{t.stocktake}</CardTitle></CardHeader><CardContent className='grid gap-3 md:grid-cols-4 md:items-end'><select aria-label={t.choose} className='h-9 w-full rounded-md border bg-background px-3 text-sm' value={selectedItem} onChange={(e) => setSelectedItem(e.target.value)}><option value=''>{t.choose}</option>{stock.map((item) => <option key={item._id} value={item._id}>{item.name}</option>)}</select><Input aria-label={t.system} readOnly value={stockRow?.currentQuantity ?? 0} placeholder={t.system} /><Input aria-label={t.actual} type='number' min='0' value={actualQuantity} onChange={(e) => setActualQuantity(e.target.value)} placeholder={t.actual} /><Button disabled={!selectedItem || addStocktake.isPending} onClick={() => addStocktake.mutate({ lines: [{ inventoryItemId: selectedItem, actualQuantity: Number(actualQuantity), reason: 'Stocktake' }] })}>{t.saveStock}</Button></CardContent></Card>}
  </div>
}
